### ISSUE TITLE
[Bug] When i loot laser robo-knight at first main mission my game is not responding

### ISSUE THREAD

**Issue by Blueberryy** [ramonDexter/WorldOfStrife#1]
I don't know if there's any log but i can try to provide it if needed

**Comment by Blueberryy** [comment]
![image](https://user-images.githubusercontent.com/36592509/219663715-5c0b4f81-21a6-49e9-8867-b21a14afd6ed.png)

**Comment by Blueberryy** [comment]
![Screenshot_Strife_20230217_182202](https://user-images.githubusercontent.com/36592509/219663775-a2c186a7-cdf2-4125-85ce-9e863494408c.png)

**Comment by ramonDexter** [comment]
This robot is not lootable, yet.
